services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api.ultrasploit.com
    restart: always
    volumes:
      - /opt/api.ultrasploit.com/app:/app/app:ro
      - /opt/api.ultrasploit.com/data/passwords.bin:/app/database/passwords.bin:ro
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.ultrasploit.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.middlewares=rate-limit-api@file"
    networks:
      - traefik

networks:
  traefik:
    external: true
